version: 3
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: pwd
      - run: flutter devices

      # - Building Apk
      - run:
          name: Build APK
          command: flutter build apk --release

      # Building Ipa's
      - run:
          name: Build IPA
          command: flutter build ios --release

      # Storing Apk -->
      - store_artifacts:
          path: build/app/outputs/apk/release/app-release.apk
          destination: app-release.apk

          # Storing ipa -->
      - store_artifacts:
          path: build/ios/iphoneos/*.ipa
          destination: app-release.ipa
