version: 3
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run: flutter doctor
      - run: pwd
      - run: flutter devices
      # - run: flutter build apk --release
      - run:
          name: Build APK
          command: flutter build apk --release
      - store_artifacts:
          path: build/app/outputs/apk/release/app-release.apk
          destination: app-release.apk
